### ISSUE TITLE
Device not closed error

### ISSUE THREAD

**Issue by manno-xx** [HaxeFoundation/haxedevelop.org#10]
Not on a windows machine myself but:
HaxeDevelop (and FlashDevelop for that matter) has a problem showing runtime errors. Running erronous code from the commandline works OK (in that is actually displays the proper error message and the stack trace leading tot the offending line of code) but Haxe-/FlashDevelop only show the "1 device not closed" error.
You can test this pretty easy by, in an OpenFL project, referring to the stage in a class' constructor ('cept for Main::new) or declaring an Int without specifying an initial value and then doing some math with it while targeting Neko.

**Comment by markknol** [comment]
Reports on the actual editor should be in the flashdevelop github, this repository is only for the website, sorry!
https://github.com/fdorg/flashdevelop/issues

**Comment by manno-xx** [comment]
My bad !
