### ISSUE TITLE
Binary stream '0' does not contain a valid BinaryHeader

### ISSUE THREAD

**Issue by hopewise** [HaxeFoundation/haxedevelop.org#12]
I've installed 5.2, I can't start it, I keep get this error:

> Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
> 
>    at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
>    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    at PluginCore.Utilities.ObjectSerializer.InternalDeserialize(String file, Type type)
>    at PluginCore.Utilities.ObjectSerializer.Deserialize(String file, Object obj, Boolean checkValidity)

**Comment by markknol** [comment]
Reports on the actual editor should be in the FlashDevelop Github, this repository is only for the website, sorry! https://github.com/fdorg/flashdevelop/issues
