### ISSUE TITLE
Parsing and scrolling too slow, almost freezing

### ISSUE THREAD

**Issue by cjdv** [HaxeFoundation/haxedevelop.org#15]
Haxedevelop 5.2 become very slow, too slow for a normal use, scrolling any document need a too long time.

I tryed this : 
- Uninstalling HaxeDevelop 5.2 & reinstall 5.2
- Disabling avast

but same problem

So i uninstall 5.2 then install 5.1 and this old version just work fine now...

I had few updates last days : nvidia & windows 10 regular updates...

**Comment by markknol** [comment]
Reports on the actual editor should be in the FlashDevelop Github, this repository is only for the website, sorry! https://github.com/fdorg/flashdevelop/issues
