### ISSUE TITLE
Domain not linked

### ISSUE THREAD

**Issue by mbndr** [HaxeFoundation/haxedevelop.org#17]
Hey, I wanted to visit the website but there are ads so I guess something with the domain is not correct?

**Comment by Fancy2209** [comment]
I believe (might be wrong) that both FlashDevelop and HaxeDevelop aren't developed anymore 
But yeah it seems the site stopped Beeing hosted

**Comment by ibilon** [comment]
You can find an archive of the website at the following url https://haxefoundation.github.io/haxedevelop.org/.
