### ISSUE TITLE
Connect -> Bug Reports menu item links to Haxe issue tracker, not HaxeDevelop issue tracker

### ISSUE THREAD

**Issue by IBwWG** [HaxeFoundation/haxedevelop.org#3]
I have a feeling that that's not where I should report HaxeDevelop issues?  I don't know where I should though, because google only brings up MattTuttle and jgranick's forks, the former of the latter, the latter of monodevelop and not having an issue tracker enabled.  (Also maybe there should be a menu item linking to this tracker too?)

**Comment by markknol** [comment]
Done!
