### ISSUE TITLE
Syntax highlight: Import with alias, "as" keyword is not highlighted as keyword

### ISSUE THREAD

**Issue by dmitry-azaraev** [HaxeFoundation/haxedevelop.org#7]
Since Haxe 3.2.0 import with alias have two forms:
1. import some.Module in ModuleAlias;
2. import some.Module as ModuleAlias;

HaxeDevelop 5.1.1.1 now is not highlight "as" keyword as keyword in second form.

**Comment by markknol** [comment]
Reports on the actual editor should be in the flashdevelop github, this repository is only for the website, sorry!
https://github.com/fdorg/flashdevelop/issues
