### ISSUE TITLE
Syntax highlight: aliased module names is not highlighted as module names

### ISSUE THREAD

**Issue by dmitry-azaraev** [HaxeFoundation/haxedevelop.org#8]
HaxeDevelop 5.1.1.1:

Now it is highlight any module names in everywhere, what is cool.
In order if we import module with alias, alias is not highlighted as module name.

**Comment by markknol** [comment]
Reports on the actual editor should be in the flashdevelop github, this repository is only for the website, sorry!
https://github.com/fdorg/flashdevelop/issues
